apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: bookstore
spec:
 replicas: 1
 template:
  metadata:
   labels:
   app: bookstore
  spec:
   containers:
   - name: bookstore
     image: <repository server>/bookstore:latest
     ports:
     - containerPort: 80
     imagePullSecrets:
     - name: regsecret

   - name: mysql
     image: mysql:5.6
     env:
     - name: MYSQL_ROOT_PASSWORD
     valueFrom:
      secretKeyRef:
        name: mysql
        key: password
     ports:
     - containerPort: 3306
       name: mysql
     volumeMounts:
     - name: mysql-persistent-storage
       mountPath: /var/lib/mysql
  volumes:
  - name: azure
    azureDisk:
      diskName: data-disk-052417233255.vhd
      diskURI: https://tjc6ysg5tzr4wmstr0.blob.core.windows.net/vhds/data-disk-052417233255.vhd
