apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: mysql

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: bookstore
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: bookstore-mysql
  spec:
   containers:
    - name: mysql
      image: mysql:5.6
      env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
         secretKeyRef:
          name: mysql
          key: password
      ports:
      - containerPort: 3306
      volumeMounts:
      - name: mysql-persistent-storage
        mountPath: /var/lib/mysql
   volumes:
    - name: mysql-persistent-storage
      azureDisk:
       diskName: <name_of_data_disk>.vhd
       diskURI: https://<storage_account>.blob.core.windows.net/vhds/<name_of_data_disk>.vhd