apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: bookstore-mysql
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: bookstore-mysql
  spec:
   containers:
    - name: mysql
      image: mysql:5.6
      env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
         secretKeyRef:
          name: mysql
          key: password
      ports:
      - containerPort: 3306
      volumeMounts:
      - name: mysql-persistent-storage
        mountPath: /var/lib/mysql
   volumes:
    - name: mysql-persistent-storage
      azureDisk:
       diskName: <disk_name>.vhd
       diskURI: https://<storageaccountname>.blob.core.windows.net/vhds/<disk_name>.vhd